using System.Collections.Generic;

namespace Intech_software.Constants
{
    internal class Zones
    {
        public static List<string> GetList()
        {
            return new List<string>()
            {
                "0",
                "1",
                "10",
                "1A",
                "2",
                "2A",
                "3",
                "4",
                "5",
                "5A",
                "6",
                "6A",
                "6B",
                "7",
                "7A",
                "8",
                "8A",
                "9",
                "9A",
                "BẮC NINH",
                "BÌNH ĐỊNH",
                "Bình Định - 49NM",
                "Bình Thuận - 113 LL",
                "Bình Thuận - 401 THĐ",
                "Cà Mau",
                "Châu Đốc",
                "ĐÀ NẴNG",
                "Đà Nẵng - 118 OIĐ",
                "Đà Nẵng – 182PĐL",
                "ĐÀ NẴNG - 18AC",
                "Đà Nẵng – 193 NT",
                "ĐÀ NẴNG - 329HD",
                "ĐÀ NẴNG - 393LD",
                "Đà Nẵng - 443 ĐBP",
                "ĐÀ NẴNG - SPA 393LD",
                "Đắk Lắk – 206NTT",
                "Đắk Lắk – 366LD",
                "Đắk Lắk – 96YJ",
                "Đắk Nông",
                "Đồng Nai - 21QL20",
                "Đồng Nai - 361 HTH",
                "Đồng Nai - 4 TN",
                "Đồng Nai - 75 3T2",
                "GIA LAI - 199HV",
                "GIA LAI - 30PDP",
                "GIFT-NG-RETURN",
                "HÀ NỘI - 105PNT",
                "Hà Nội - 219KT",
                "Hà Nội – 268NH",
                "Hà Nội - 302NT",
                "HÀ NỘI - 40BM",
                "HÀ NỘI - 594NVC",
                "Hà Nội -169TH",
                "Hà Nội-182CG",
                "Hà Tiên",
                "HÀ TĨNH",
                "Hải Phòng",
                "Hồng Ngự",
                "HUẾ - 146HV",
                "Huế – 59 MTL",
                "HUẾ 76BT",
                "Khánh Hòa – 2203 HV",
                "Khánh Hòa - 389 2T4",
                "Khánh Hòa – 58 LTT",
                "KON TUM",
                "Lâm Đồng - 1 HBT",
                "Lâm Đồng - 10HV",
                "Lâm Đồng - 179 PCT",
                "Lâm Đồng - 284 BTX",
                "Lâm Đồng - 542 QL20",
                "Lâm Đồng - 63LHP",
                "NG-22-TAN-THOI-NHAT",
                "Nghệ An - 11 QT",
                "Nghệ An - 217 NVC",
                "Ninh Thuận – 562 TN",
                "PHÚ QUỐC",
                "PHÚ YÊN",
                "Quảng Bình – 158THĐ",
                "QUẢNG NAM",
                "QUẢNG NGÃI",
                "QUẢNG TRỊ",
                "SHOPEE",
                "SPA - GENERAL",
                "THÁI NGUYÊN",
                "THANH HÓA",
                "Zone 1",
                "Zone 2",
                "Zone 2A",
                "Zone 3",
                "Zone 4",
                "Zone 5",
                "Zone 6",
                "zone 9",
                "Zone Đà Nẵng - 393LD",
                "Zone Hà Nội - 182CG",
                "KT",
            };
        }
    }
}
